# Generated by Django 3.0.6 on 2020-06-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200614_1845'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='api_agent',
        ),
        migrations.AlterModelTable(
            name='event',
            table='api_event',
        ),
        migrations.AlterModelTable(
            name='group',
            table='api_group',
        ),
        migrations.AlterModelTable(
            name='groupuser',
            table='api_groupuser',
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
