# Generated by Django 3.0.6 on 2020-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200614_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], max_length=20),
        ),
    ]
