# Generated by Django 2.2.4 on 2020-07-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='api_agent',
        ),
        migrations.AlterModelTable(
            name='event',
            table='api_event',
        ),
        migrations.AlterModelTable(
            name='group',
            table='api_group',
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
